# Generated by Django 3.0.6 on 2020-05-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprascombos',
            options={'ordering': ['cantidad'], 'verbose_name': 'Compras Combos', 'verbose_name_plural': 'Compras Combos'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['fecha_compra'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
