# Generated by Django 3.0.6 on 2020-05-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
