# Generated by Django 3.0.6 on 2020-05-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0002_delete_pelicula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ['nombre'], 'verbose_name': 'Combo', 'verbose_name_plural': 'Combos'},
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['tipo'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
