# Generated by Django 3.0.6 on 2020-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0003_auto_20200530_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.AlterField(
            model_name='combo',
            name='precio',
            field=models.FloatField(),
        ),
    ]
