# Generated by Django 3.0.6 on 2020-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('fecha_estreno', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('duracion', models.TimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
