# Generated by Django 3.0.6 on 2020-06-03 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['id_sala'],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('butacas_disponibles', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('fecha_estreno', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('duracion', models.TimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sala', models.CharField(max_length=200)),
                ('numero_filas', models.IntegerField()),
                ('numero_columnas', models.IntegerField()),
                ('imagen', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['tipo_sala'],
            },
        ),
        migrations.CreateModel(
            name='ReservarAsientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Asiento')),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Funcion')),
            ],
            options={
                'verbose_name': 'Reservación de Asiento',
                'verbose_name_plural': 'Reservación Asientos',
                'ordering': ['id_funcion'],
            },
        ),
        migrations.AddField(
            model_name='funcion',
            name='id_pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Pelicula'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Funcion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='ComprasEntradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Asiento')),
                ('id_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Entrada')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasCombos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_combos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Combo')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
            ],
            options={
                'verbose_name': 'Compras Combos',
                'verbose_name_plural': 'Compras Combos',
                'ordering': ['cantidad'],
            },
        ),
        migrations.AddField(
            model_name='asiento',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala'),
        ),
    ]
