# Generated by Django 3.0.6 on 2020-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=20)),
                ('cedula', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='comprascombos',
            name='id_combos',
        ),
        migrations.RemoveField(
            model_name='comprascombos',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='comprasentradas',
            name='id_asiento',
        ),
        migrations.RemoveField(
            model_name='comprasentradas',
            name='id_entrada',
        ),
        migrations.RemoveField(
            model_name='comprasentradas',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_funcion',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='ComprasCombos',
        ),
        migrations.DeleteModel(
            name='ComprasEntradas',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
