# Generated by Django 3.0.6 on 2020-05-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_auto_20200528_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('butacas_disponibles', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sala', models.CharField(max_length=200)),
                ('numero_filas', models.IntegerField()),
                ('numero_columnas', models.IntegerField()),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAsientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Asiento')),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Funcion')),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala'),
        ),
    ]
