# Generated by Django 3.0.6 on 2020-06-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_auto_20200602_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
