# Generated by Django 3.0.6 on 2020-06-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0004_registrocombos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='puntos_usados',
            field=models.IntegerField(default=0),
        ),
    ]
