# Generated by Django 3.0.6 on 2020-05-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0005_auto_20200530_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['titulo'], 'verbose_name': 'Peliculaaaaa', 'verbose_name_plural': 'Peliculassss'},
        ),
    ]
