# Generated by Django 3.0.6 on 2020-06-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0006_auto_20200622_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
