# Generated by Django 3.0.6 on 2020-06-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0007_auto_20200622_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='promociones',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='registrocombos',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puntos',
        ),
        migrations.AddField(
            model_name='promociones',
            name='fecha_fin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promociones',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Producto')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Empleados',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_permisos', models.BooleanField(default=False)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sucursal')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='ComboCine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('descuento', models.FloatField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Producto')),
            ],
            options={
                'verbose_name': 'Combo Cine',
                'verbose_name_plural': 'Combos Cine',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
                'ordering': ['puntos'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_neto', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Producto')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
