# Generated by Django 3.0.6 on 2020-06-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0008_auto_20200530_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Funcion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='ComprasEntradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Asiento')),
                ('id_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Entrada')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasCombos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_combos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Combo')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
            ],
            options={
                'verbose_name': 'Compras Combos',
                'verbose_name_plural': 'Compras Combos',
                'ordering': ['cantidad'],
            },
        ),
    ]
