# Generated by Django 3.0.6 on 2020-06-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0008_auto_20200629_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['tipo'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='registroasientosreservados',
            options={'verbose_name': 'Registro Asiento Reservado', 'verbose_name_plural': 'Registros Asientos Reservados'},
        ),
        migrations.AlterModelOptions(
            name='registrocategorias',
            options={'verbose_name': 'Reistro Categoria', 'verbose_name_plural': 'Registro Categorias'},
        ),
        migrations.AlterModelOptions(
            name='registrocombos',
            options={'verbose_name': 'Registro Combo', 'verbose_name_plural': 'Registro Combos'},
        ),
        migrations.AlterModelOptions(
            name='registrocompras',
            options={'verbose_name': 'Registro Compra', 'verbose_name_plural': 'Registros Compras'},
        ),
        migrations.AlterModelOptions(
            name='registropromociones',
            options={'verbose_name': 'Registro Promoción', 'verbose_name_plural': 'Registros Promociones'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
