# Generated by Django 3.0.6 on 2020-06-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0009_combo_comprascombos_comprasentradas_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprascombos',
            options={'ordering': ['cantidad'], 'verbose_name': 'Compra Combo', 'verbose_name_plural': 'Compras Combos'},
        ),
        migrations.AlterModelOptions(
            name='comprasentradas',
            options={'ordering': ['id_factura'], 'verbose_name': 'Compra Entrada', 'verbose_name_plural': 'Compras Entradas'},
        ),
    ]
