# Generated by Django 3.0.6 on 2020-06-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0010_auto_20200602_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprascombos',
            options={'ordering': ['id_factura'], 'verbose_name': 'Compra Combo', 'verbose_name_plural': 'Compras Combos'},
        ),
    ]
