# Generated by Django 3.0.6 on 2020-06-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0013_auto_20200602_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
