# Generated by Django 3.0.6 on 2020-07-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0013_auto_20200706_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_tipos_productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.TipoProductos'),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
