# Generated by Django 3.0.6 on 2020-06-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0014_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('contrasena', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puntos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
        ),
    ]
