# Generated by Django 3.0.6 on 2020-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0015_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(max_length=15),
        ),
    ]
