# Generated by Django 3.0.6 on 2020-06-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0018_auto_20200602_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprascombos',
            name='id_combos',
        ),
        migrations.RemoveField(
            model_name='comprascombos',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='comprasentradas',
            name='id_asiento',
        ),
        migrations.RemoveField(
            model_name='comprasentradas',
            name='id_entrada',
        ),
        migrations.RemoveField(
            model_name='comprasentradas',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_funcion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='id_pelicula',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='id_sala',
        ),
        migrations.RemoveField(
            model_name='reservarasientos',
            name='id_asiento',
        ),
        migrations.RemoveField(
            model_name='reservarasientos',
            name='id_funcion',
        ),
        migrations.DeleteModel(
            name='Asiento',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='ComprasCombos',
        ),
        migrations.DeleteModel(
            name='ComprasEntradas',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Funcion',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='ReservarAsientos',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
