# Generated by Django 3.0.6 on 2020-06-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0023_sala_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('butacas_disponibles', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Pelicula')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala')),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['id_sala'],
            },
        ),
    ]
