# Generated by Django 3.0.6 on 2020-06-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0024_asiento_funcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipoProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='registroCombos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipos_productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.tipoProductos'),
        ),
    ]
