# Generated by Django 3.0.6 on 2020-06-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0026_factura_promociones'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroPromociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_aplicado', models.FloatField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
                ('id_promociones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Promociones')),
            ],
        ),
    ]
