# Generated by Django 3.0.6 on 2020-06-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0027_registropromociones'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='registroAsientosReservados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Asiento')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Factura')),
                ('id_funciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Funcion')),
            ],
        ),
    ]
