# Generated by Django 3.0.6 on 2020-06-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0028_registroasientosreservados_registrocompras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='promociones',
            options={'ordering': ['nombre'], 'verbose_name': 'Promocion', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tipoproductos',
            options={'ordering': ['tipo'], 'verbose_name': 'Tipo Producto', 'verbose_name_plural': 'Tipo Productos'},
        ),
    ]
